apiVersion: kubeadm.k8s.io/v1beta3
kind: InitConfiguration
localAPIEndpoint:
  advertiseAddress: ${api_advertise_address}
  bindPort: 6443
nodeRegistration:
  criSocket: unix:///var/run/containerd/containerd.sock
---
apiVersion: kubeadm.k8s.io/v1beta3
kind: ClusterConfiguration
kubernetesVersion: v1.33.0
certificatesDir: /etc/kubernetes/pki
apiServer:
  certSANs:
  ${cert_sans}
  extraArgs:
    ${indent(4, apiserver_extra_args)}
  extraVolumes:
    ${indent(4, apiserver_extra_volumes)}
etcd:
  external:
    endpoints:
    ${etcd_endpoints}
---
apiVersion: kubelet.config.k8s.io/v1beta1
kind: KubeletConfiguration
failSwapOn: false
cgroupDriver: systemd
${kubelet_extra_config}
